export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const LANGUAGE_ACTIONS = {
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
};

export const LAYOUT_ACTIONS = {
  LOAD_MENU: 'LOAD_MENU',
  LOAD_BASICS: 'LOAD_BASICS',
  LOAD_DETAIL: 'LOAD_DETAIL',
};
